///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JavaSwingdemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JavaSwingdemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("898e5237-c47f-48d4-9c52-4a9715961128")]
    public partial class JavaSwingdemoRepository : RepoGenBaseFolder
    {
        static JavaSwingdemoRepository instance = new JavaSwingdemoRepository();
        JavaSwingdemoRepositoryFolders.SwingSet3AppFolder _swingset3;
        JavaSwingdemoRepositoryFolders.InputAppFolder _input;
        JavaSwingdemoRepositoryFolders.MessageAppFolder _message;
        JavaSwingdemoRepositoryFolders.WarningDialogExampleAppFolder _warningdialogexample;
        JavaSwingdemoRepositoryFolders.ComponentDialogExampleAppFolder _componentdialogexample;
        JavaSwingdemoRepositoryFolders.SelectAnOptionAppFolder _selectanoption;

        /// <summary>
        /// Gets the singleton class instance representing the JavaSwingdemoRepository element repository.
        /// </summary>
        [RepositoryFolder("898e5237-c47f-48d4-9c52-4a9715961128")]
        public static JavaSwingdemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JavaSwingdemoRepository() 
            : base("JavaSwingdemoRepository", "/", null, 0, false, "898e5237-c47f-48d4-9c52-4a9715961128", ".\\RepositoryImages\\JavaSwingdemoRepository898e5237.rximgres")
        {
            _swingset3 = new JavaSwingdemoRepositoryFolders.SwingSet3AppFolder(this);
            _input = new JavaSwingdemoRepositoryFolders.InputAppFolder(this);
            _message = new JavaSwingdemoRepositoryFolders.MessageAppFolder(this);
            _warningdialogexample = new JavaSwingdemoRepositoryFolders.WarningDialogExampleAppFolder(this);
            _componentdialogexample = new JavaSwingdemoRepositoryFolders.ComponentDialogExampleAppFolder(this);
            _selectanoption = new JavaSwingdemoRepositoryFolders.SelectAnOptionAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("898e5237-c47f-48d4-9c52-4a9715961128")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SwingSet3 folder.
        /// </summary>
        [RepositoryFolder("e1d15bcc-409b-4132-9887-c4e830adf3e0")]
        public virtual JavaSwingdemoRepositoryFolders.SwingSet3AppFolder SwingSet3
        {
            get { return _swingset3; }
        }

        /// <summary>
        /// The Input folder.
        /// </summary>
        [RepositoryFolder("5c59db4f-8343-4b58-8f9a-58e43ec1f937")]
        public virtual JavaSwingdemoRepositoryFolders.InputAppFolder Input
        {
            get { return _input; }
        }

        /// <summary>
        /// The Message folder.
        /// </summary>
        [RepositoryFolder("dc233879-7e48-4464-ae48-35be73e44c70")]
        public virtual JavaSwingdemoRepositoryFolders.MessageAppFolder Message
        {
            get { return _message; }
        }

        /// <summary>
        /// The WarningDialogExample folder.
        /// </summary>
        [RepositoryFolder("96cef0df-2d59-4f56-83aa-55db97d7f0f6")]
        public virtual JavaSwingdemoRepositoryFolders.WarningDialogExampleAppFolder WarningDialogExample
        {
            get { return _warningdialogexample; }
        }

        /// <summary>
        /// The ComponentDialogExample folder.
        /// </summary>
        [RepositoryFolder("1c7c8784-0e78-4b5b-acf2-6bdd39cac17c")]
        public virtual JavaSwingdemoRepositoryFolders.ComponentDialogExampleAppFolder ComponentDialogExample
        {
            get { return _componentdialogexample; }
        }

        /// <summary>
        /// The SelectAnOption folder.
        /// </summary>
        [RepositoryFolder("e29b5418-dcfb-459d-b517-dac5dad44659")]
        public virtual JavaSwingdemoRepositoryFolders.SelectAnOptionAppFolder SelectAnOption
        {
            get { return _selectanoption; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class JavaSwingdemoRepositoryFolders
    {
        /// <summary>
        /// The SwingSet3AppFolder folder.
        /// </summary>
        [RepositoryFolder("e1d15bcc-409b-4132-9887-c4e830adf3e0")]
        public partial class SwingSet3AppFolder : RepoGenBaseFolder
        {
            JavaSwingdemoRepositoryFolders.JPanelFolder _jpanel;
            RepoItemInfo _jbuttonInfo;

            /// <summary>
            /// Creates a new SwingSet3  folder.
            /// </summary>
            public SwingSet3AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SwingSet3", "/form[@title='SwingSet3']", parentFolder, 30000, null, false, "e1d15bcc-409b-4132-9887-c4e830adf3e0", "")
            {
                _jpanel = new JavaSwingdemoRepositoryFolders.JPanelFolder(this);
                _jbuttonInfo = new RepoItemInfo(this, "JButton", ".//container[@name='scrollPane']/.//checkbox[@text='JButton ' and @visible='True']", 30000, null, "6b12de86-807b-40b9-bc5b-24ab050b5816");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e1d15bcc-409b-4132-9887-c4e830adf3e0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e1d15bcc-409b-4132-9887-c4e830adf3e0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JButton item.
            /// </summary>
            [RepositoryItem("6b12de86-807b-40b9-bc5b-24ab050b5816")]
            public virtual Ranorex.CheckBox JButton
            {
                get
                {
                    return _jbuttonInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The JButton item info.
            /// </summary>
            [RepositoryItemInfo("6b12de86-807b-40b9-bc5b-24ab050b5816")]
            public virtual RepoItemInfo JButtonInfo
            {
                get
                {
                    return _jbuttonInfo;
                }
            }

            /// <summary>
            /// The JPanel folder.
            /// </summary>
            [RepositoryFolder("c1c3ce62-555c-4d6c-b9ba-a9920ebcb09f")]
            public virtual JavaSwingdemoRepositoryFolders.JPanelFolder JPanel
            {
                get { return _jpanel; }
            }
        }

        /// <summary>
        /// The JPanelFolder folder.
        /// </summary>
        [RepositoryFolder("c1c3ce62-555c-4d6c-b9ba-a9920ebcb09f")]
        public partial class JPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textfieldInfo;
            RepoItemInfo _joptionpaneInfo;
            RepoItemInfo _doitagainInfo;
            RepoItemInfo _doitInfo;
            RepoItemInfo _showcomponentdialogInfo;
            RepoItemInfo _showconfirmationdialogInfo;
            RepoItemInfo _showinputdialogInfo;
            RepoItemInfo _showmessagedialogInfo;
            RepoItemInfo _showwarningdialogInfo;
            RepoItemInfo _buttongoInfo;
            RepoItemInfo _tfpassword1Info;
            RepoItemInfo _tfpassword2Info;

            /// <summary>
            /// Creates a new JPanel  folder.
            /// </summary>
            public JPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("JPanel", "container[@type='JPanel']", parentFolder, 30000, null, false, "c1c3ce62-555c-4d6c-b9ba-a9920ebcb09f", "")
            {
                _textfieldInfo = new RepoItemInfo(this, "TextField", ".//checkbox[@text='TextField ']", 30000, null, "0d48da7e-63b6-46a3-9f88-c308fde856ee");
                _joptionpaneInfo = new RepoItemInfo(this, "JOptionPane", ".//checkbox[@text='JOptionPane ']", 30000, null, "f2303f65-d5c8-4405-8be1-0dcae288533f");
                _doitagainInfo = new RepoItemInfo(this, "DoItAgain", ".//button[@text='Do it again']", 30000, null, "bc5cd38f-3a8b-4ab1-b2e6-ad802fc41642");
                _doitInfo = new RepoItemInfo(this, "DoIt", ".//button[@text~'^Do it']", 30000, null, "e9de5dbc-e2f3-4ef3-b755-27aead15fe7d");
                _showcomponentdialogInfo = new RepoItemInfo(this, "ShowComponentDialog", ".//button[@text='Show Component Dialog']", 30000, null, "c37dbfa6-f8f6-406e-8d7e-ce188b6876f4");
                _showconfirmationdialogInfo = new RepoItemInfo(this, "ShowConfirmationDialog", ".//button[@text='Show Confirmation Dialog']", 30000, null, "b047089b-02d5-4500-8e80-fe21e98951b4");
                _showinputdialogInfo = new RepoItemInfo(this, "ShowInputDialog", ".//button[@text='Show Input Dialog']", 30000, null, "a1ef3a33-fbe4-49a1-b822-3a048ceb4935");
                _showmessagedialogInfo = new RepoItemInfo(this, "ShowMessageDialog", ".//button[@text='Show Message Dialog']", 30000, null, "f1736dd2-7372-4f04-af3e-ea1fea6a1518");
                _showwarningdialogInfo = new RepoItemInfo(this, "ShowWarningDialog", ".//button[@text='Show Warning Dialog']", 30000, null, "cb46cbca-bde0-42c6-9b51-ed387d6863e2");
                _buttongoInfo = new RepoItemInfo(this, "ButtonGo", ".//button[@name='btnGo']", 30000, null, "5fed8819-a972-4653-8d6f-b2f5d9f47da4");
                _tfpassword1Info = new RepoItemInfo(this, "TfPassword1", ".//text[@name='tfPassword1']", 30000, null, "5a4eca06-0f19-47e1-a820-5e36d93f8b18");
                _tfpassword2Info = new RepoItemInfo(this, "TfPassword2", ".//text[@name='tfPassword2']", 30000, null, "976923eb-bce8-4b93-8fa2-0a9e575859d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1c3ce62-555c-4d6c-b9ba-a9920ebcb09f")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1c3ce62-555c-4d6c-b9ba-a9920ebcb09f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextField item.
            /// </summary>
            [RepositoryItem("0d48da7e-63b6-46a3-9f88-c308fde856ee")]
            public virtual Ranorex.CheckBox TextField
            {
                get
                {
                    return _textfieldInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The TextField item info.
            /// </summary>
            [RepositoryItemInfo("0d48da7e-63b6-46a3-9f88-c308fde856ee")]
            public virtual RepoItemInfo TextFieldInfo
            {
                get
                {
                    return _textfieldInfo;
                }
            }

            /// <summary>
            /// The JOptionPane item.
            /// </summary>
            [RepositoryItem("f2303f65-d5c8-4405-8be1-0dcae288533f")]
            public virtual Ranorex.CheckBox JOptionPane
            {
                get
                {
                    return _joptionpaneInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The JOptionPane item info.
            /// </summary>
            [RepositoryItemInfo("f2303f65-d5c8-4405-8be1-0dcae288533f")]
            public virtual RepoItemInfo JOptionPaneInfo
            {
                get
                {
                    return _joptionpaneInfo;
                }
            }

            /// <summary>
            /// The DoItAgain item.
            /// </summary>
            [RepositoryItem("bc5cd38f-3a8b-4ab1-b2e6-ad802fc41642")]
            public virtual Ranorex.Button DoItAgain
            {
                get
                {
                    return _doitagainInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DoItAgain item info.
            /// </summary>
            [RepositoryItemInfo("bc5cd38f-3a8b-4ab1-b2e6-ad802fc41642")]
            public virtual RepoItemInfo DoItAgainInfo
            {
                get
                {
                    return _doitagainInfo;
                }
            }

            /// <summary>
            /// The DoIt item.
            /// </summary>
            [RepositoryItem("e9de5dbc-e2f3-4ef3-b755-27aead15fe7d")]
            public virtual Ranorex.Button DoIt
            {
                get
                {
                    return _doitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DoIt item info.
            /// </summary>
            [RepositoryItemInfo("e9de5dbc-e2f3-4ef3-b755-27aead15fe7d")]
            public virtual RepoItemInfo DoItInfo
            {
                get
                {
                    return _doitInfo;
                }
            }

            /// <summary>
            /// The ShowComponentDialog item.
            /// </summary>
            [RepositoryItem("c37dbfa6-f8f6-406e-8d7e-ce188b6876f4")]
            public virtual Ranorex.Button ShowComponentDialog
            {
                get
                {
                    return _showcomponentdialogInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShowComponentDialog item info.
            /// </summary>
            [RepositoryItemInfo("c37dbfa6-f8f6-406e-8d7e-ce188b6876f4")]
            public virtual RepoItemInfo ShowComponentDialogInfo
            {
                get
                {
                    return _showcomponentdialogInfo;
                }
            }

            /// <summary>
            /// The ShowConfirmationDialog item.
            /// </summary>
            [RepositoryItem("b047089b-02d5-4500-8e80-fe21e98951b4")]
            public virtual Ranorex.Button ShowConfirmationDialog
            {
                get
                {
                    return _showconfirmationdialogInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShowConfirmationDialog item info.
            /// </summary>
            [RepositoryItemInfo("b047089b-02d5-4500-8e80-fe21e98951b4")]
            public virtual RepoItemInfo ShowConfirmationDialogInfo
            {
                get
                {
                    return _showconfirmationdialogInfo;
                }
            }

            /// <summary>
            /// The ShowInputDialog item.
            /// </summary>
            [RepositoryItem("a1ef3a33-fbe4-49a1-b822-3a048ceb4935")]
            public virtual Ranorex.Button ShowInputDialog
            {
                get
                {
                    return _showinputdialogInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShowInputDialog item info.
            /// </summary>
            [RepositoryItemInfo("a1ef3a33-fbe4-49a1-b822-3a048ceb4935")]
            public virtual RepoItemInfo ShowInputDialogInfo
            {
                get
                {
                    return _showinputdialogInfo;
                }
            }

            /// <summary>
            /// The ShowMessageDialog item.
            /// </summary>
            [RepositoryItem("f1736dd2-7372-4f04-af3e-ea1fea6a1518")]
            public virtual Ranorex.Button ShowMessageDialog
            {
                get
                {
                    return _showmessagedialogInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShowMessageDialog item info.
            /// </summary>
            [RepositoryItemInfo("f1736dd2-7372-4f04-af3e-ea1fea6a1518")]
            public virtual RepoItemInfo ShowMessageDialogInfo
            {
                get
                {
                    return _showmessagedialogInfo;
                }
            }

            /// <summary>
            /// The ShowWarningDialog item.
            /// </summary>
            [RepositoryItem("cb46cbca-bde0-42c6-9b51-ed387d6863e2")]
            public virtual Ranorex.Button ShowWarningDialog
            {
                get
                {
                    return _showwarningdialogInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShowWarningDialog item info.
            /// </summary>
            [RepositoryItemInfo("cb46cbca-bde0-42c6-9b51-ed387d6863e2")]
            public virtual RepoItemInfo ShowWarningDialogInfo
            {
                get
                {
                    return _showwarningdialogInfo;
                }
            }

            /// <summary>
            /// The ButtonGo item.
            /// </summary>
            [RepositoryItem("5fed8819-a972-4653-8d6f-b2f5d9f47da4")]
            public virtual Ranorex.Button ButtonGo
            {
                get
                {
                    return _buttongoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonGo item info.
            /// </summary>
            [RepositoryItemInfo("5fed8819-a972-4653-8d6f-b2f5d9f47da4")]
            public virtual RepoItemInfo ButtonGoInfo
            {
                get
                {
                    return _buttongoInfo;
                }
            }

            /// <summary>
            /// The TfPassword1 item.
            /// </summary>
            [RepositoryItem("5a4eca06-0f19-47e1-a820-5e36d93f8b18")]
            public virtual Ranorex.Text TfPassword1
            {
                get
                {
                    return _tfpassword1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TfPassword1 item info.
            /// </summary>
            [RepositoryItemInfo("5a4eca06-0f19-47e1-a820-5e36d93f8b18")]
            public virtual RepoItemInfo TfPassword1Info
            {
                get
                {
                    return _tfpassword1Info;
                }
            }

            /// <summary>
            /// The TfPassword2 item.
            /// </summary>
            [RepositoryItem("976923eb-bce8-4b93-8fa2-0a9e575859d5")]
            public virtual Ranorex.Text TfPassword2
            {
                get
                {
                    return _tfpassword2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TfPassword2 item info.
            /// </summary>
            [RepositoryItemInfo("976923eb-bce8-4b93-8fa2-0a9e575859d5")]
            public virtual RepoItemInfo TfPassword2Info
            {
                get
                {
                    return _tfpassword2Info;
                }
            }
        }

        /// <summary>
        /// The InputAppFolder folder.
        /// </summary>
        [RepositoryFolder("5c59db4f-8343-4b58-8f9a-58e43ec1f937")]
        public partial class InputAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _optionpanetextfieldInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Input  folder.
            /// </summary>
            public InputAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Input", "/form[@title='Input']", parentFolder, 30000, null, false, "5c59db4f-8343-4b58-8f9a-58e43ec1f937", "")
            {
                _optionpanetextfieldInfo = new RepoItemInfo(this, "OptionPaneTextField", "?/?/container[@name='OptionPane.messageArea']/container[@name='OptionPane.realBody']/?/?/text[@name='OptionPane.textField']", 30000, null, "cf4ed82a-2ba8-401a-a718-0c16a23bec22");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/container[@name='OptionPane.buttonArea']/button[@text='OK']", 30000, null, "16ed5311-0de4-4c32-b15e-391ea2a7ae99");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c59db4f-8343-4b58-8f9a-58e43ec1f937")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c59db4f-8343-4b58-8f9a-58e43ec1f937")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OptionPaneTextField item.
            /// </summary>
            [RepositoryItem("cf4ed82a-2ba8-401a-a718-0c16a23bec22")]
            public virtual Ranorex.Text OptionPaneTextField
            {
                get
                {
                    return _optionpanetextfieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OptionPaneTextField item info.
            /// </summary>
            [RepositoryItemInfo("cf4ed82a-2ba8-401a-a718-0c16a23bec22")]
            public virtual RepoItemInfo OptionPaneTextFieldInfo
            {
                get
                {
                    return _optionpanetextfieldInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("16ed5311-0de4-4c32-b15e-391ea2a7ae99")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("16ed5311-0de4-4c32-b15e-391ea2a7ae99")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The MessageAppFolder folder.
        /// </summary>
        [RepositoryFolder("dc233879-7e48-4464-ae48-35be73e44c70")]
        public partial class MessageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Message  folder.
            /// </summary>
            public MessageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Message", "/form[@title='Message']", parentFolder, 30000, null, false, "dc233879-7e48-4464-ae48-35be73e44c70", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/container[@name='OptionPane.buttonArea']/button[@name='OptionPane.button']", 30000, null, "8603a6f2-e88f-4627-af32-74775ff0a1d2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dc233879-7e48-4464-ae48-35be73e44c70")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc233879-7e48-4464-ae48-35be73e44c70")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("8603a6f2-e88f-4627-af32-74775ff0a1d2")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("8603a6f2-e88f-4627-af32-74775ff0a1d2")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The WarningDialogExampleAppFolder folder.
        /// </summary>
        [RepositoryFolder("96cef0df-2d59-4f56-83aa-55db97d7f0f6")]
        public partial class WarningDialogExampleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new WarningDialogExample  folder.
            /// </summary>
            public WarningDialogExampleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WarningDialogExample", "/form[@title='Warning Dialog Example']", parentFolder, 30000, null, false, "96cef0df-2d59-4f56-83aa-55db97d7f0f6", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/container[@name='OptionPane.buttonArea']/button[@name='OptionPane.button']", 30000, null, "ff4a55f0-84e4-4f6b-a4eb-cfa969cb31cf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("96cef0df-2d59-4f56-83aa-55db97d7f0f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("96cef0df-2d59-4f56-83aa-55db97d7f0f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("ff4a55f0-84e4-4f6b-a4eb-cfa969cb31cf")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("ff4a55f0-84e4-4f6b-a4eb-cfa969cb31cf")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The ComponentDialogExampleAppFolder folder.
        /// </summary>
        [RepositoryFolder("1c7c8784-0e78-4b5b-acf2-6bdd39cac17c")]
        public partial class ComponentDialogExampleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jcomboboxInfo;
            RepoItemInfo _item2Info;
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new ComponentDialogExample  folder.
            /// </summary>
            public ComponentDialogExampleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComponentDialogExample", "/form[@title='Component Dialog Example']", parentFolder, 30000, null, false, "1c7c8784-0e78-4b5b-acf2-6bdd39cac17c", "")
            {
                _jcomboboxInfo = new RepoItemInfo(this, "JComboBox", "?/?/container[@name='OptionPane.messageArea']/container[@name='OptionPane.realBody']/?/?/combobox[@type='JComboBox']", 30000, null, "aa3bb12f-05bd-489f-95ed-6bfca3284f42");
                _item2Info = new RepoItemInfo(this, "Item2", "contextmenu[@name='ComboPopup.popup']//list[@name='ComboBox.list']/listitem[@text='item 2']", 30000, null, "a6aeb1f9-e0fb-4325-8766-0152e32f43fb");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "?/?/container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "6411ab3d-3293-40a8-82ba-fea1a3130dae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1c7c8784-0e78-4b5b-acf2-6bdd39cac17c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1c7c8784-0e78-4b5b-acf2-6bdd39cac17c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JComboBox item.
            /// </summary>
            [RepositoryItem("aa3bb12f-05bd-489f-95ed-6bfca3284f42")]
            public virtual Ranorex.ComboBox JComboBox
            {
                get
                {
                    return _jcomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The JComboBox item info.
            /// </summary>
            [RepositoryItemInfo("aa3bb12f-05bd-489f-95ed-6bfca3284f42")]
            public virtual RepoItemInfo JComboBoxInfo
            {
                get
                {
                    return _jcomboboxInfo;
                }
            }

            /// <summary>
            /// The Item2 item.
            /// </summary>
            [RepositoryItem("a6aeb1f9-e0fb-4325-8766-0152e32f43fb")]
            public virtual Ranorex.ListItem Item2
            {
                get
                {
                    return _item2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Item2 item info.
            /// </summary>
            [RepositoryItemInfo("a6aeb1f9-e0fb-4325-8766-0152e32f43fb")]
            public virtual RepoItemInfo Item2Info
            {
                get
                {
                    return _item2Info;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("6411ab3d-3293-40a8-82ba-fea1a3130dae")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("6411ab3d-3293-40a8-82ba-fea1a3130dae")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The SelectAnOptionAppFolder folder.
        /// </summary>
        [RepositoryFolder("e29b5418-dcfb-459d-b517-dac5dad44659")]
        public partial class SelectAnOptionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new SelectAnOption  folder.
            /// </summary>
            public SelectAnOptionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectAnOption", "/form[@title='Select an Option']", parentFolder, 30000, null, false, "e29b5418-dcfb-459d-b517-dac5dad44659", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "?/?/container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "4e8c0114-9f91-4e6a-b587-9452a6bd85b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e29b5418-dcfb-459d-b517-dac5dad44659")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e29b5418-dcfb-459d-b517-dac5dad44659")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("4e8c0114-9f91-4e6a-b587-9452a6bd85b3")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("4e8c0114-9f91-4e6a-b587-9452a6bd85b3")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}