///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace JavaSwingdemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("a9677fcb-8596-4cbc-bdf2-f42a8a68c787", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the JavaSwingdemoRepository repository.
        /// </summary>
        public static JavaSwingdemoRepository repo = JavaSwingdemoRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking Activate() on item 'SwingSet3'.", repo.SwingSet3.SelfInfo, new RecordItemIndex(0));
            //repo.SwingSet3.Self.Activate();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking Maximize() on item 'SwingSet3'.", repo.SwingSet3.SelfInfo, new RecordItemIndex(1));
            //repo.SwingSet3.Self.Maximize();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.JOptionPane' at 86;13.", repo.SwingSet3.JPanel.JOptionPaneInfo, new RecordItemIndex(2));
            repo.SwingSet3.JPanel.JOptionPane.Click("86;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.ShowInputDialog' at 101;13.", repo.SwingSet3.JPanel.ShowInputDialogInfo, new RecordItemIndex(3));
            repo.SwingSet3.JPanel.ShowInputDialog.Click("101;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Input.OptionPaneTextField' at 18;16.", repo.Input.OptionPaneTextFieldInfo, new RecordItemIndex(4));
            repo.Input.OptionPaneTextField.Click("18;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello'.", new RecordItemIndex(5));
            Keyboard.Press("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Input.ButtonOK' at 21;10.", repo.Input.ButtonOKInfo, new RecordItemIndex(6));
            repo.Input.ButtonOK.Click("21;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Message.ButtonOK' at 27;12.", repo.Message.ButtonOKInfo, new RecordItemIndex(7));
            repo.Message.ButtonOK.Click("27;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.ShowWarningDialog' at 91;14.", repo.SwingSet3.JPanel.ShowWarningDialogInfo, new RecordItemIndex(8));
            repo.SwingSet3.JPanel.ShowWarningDialog.Click("91;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WarningDialogExample.ButtonOK' at 24;14.", repo.WarningDialogExample.ButtonOKInfo, new RecordItemIndex(9));
            repo.WarningDialogExample.ButtonOK.Click("24;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.ShowMessageDialog' at 91;12.", repo.SwingSet3.JPanel.ShowMessageDialogInfo, new RecordItemIndex(10));
            repo.SwingSet3.JPanel.ShowMessageDialog.Click("91;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Message.ButtonOK' at 26;9.", repo.Message.ButtonOKInfo, new RecordItemIndex(11));
            repo.Message.ButtonOK.Click("26;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.ShowComponentDialog' at 106;14.", repo.SwingSet3.JPanel.ShowComponentDialogInfo, new RecordItemIndex(12));
            repo.SwingSet3.JPanel.ShowComponentDialog.Click("106;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ComponentDialogExample.JComboBox' at 52;15.", repo.ComponentDialogExample.JComboBoxInfo, new RecordItemIndex(13));
            repo.ComponentDialogExample.JComboBox.Click("52;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ComponentDialogExample.Item2' at 41;9.", repo.ComponentDialogExample.Item2Info, new RecordItemIndex(14));
            repo.ComponentDialogExample.Item2.Click("41;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ComponentDialogExample.ButtonYes' at 18;18.", repo.ComponentDialogExample.ButtonYesInfo, new RecordItemIndex(15));
            repo.ComponentDialogExample.ButtonYes.Click("18;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Message.ButtonOK' at 23;12.", repo.Message.ButtonOKInfo, new RecordItemIndex(16));
            repo.Message.ButtonOK.Click("23;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.ShowConfirmationDialog' at 87;16.", repo.SwingSet3.JPanel.ShowConfirmationDialogInfo, new RecordItemIndex(17));
            repo.SwingSet3.JPanel.ShowConfirmationDialog.Click("87;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectAnOption.ButtonYes' at 21;11.", repo.SelectAnOption.ButtonYesInfo, new RecordItemIndex(18));
            repo.SelectAnOption.ButtonYes.Click("21;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Message.ButtonOK' at 31;9.", repo.Message.ButtonOKInfo, new RecordItemIndex(19));
            repo.Message.ButtonOK.Click("31;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JButton' at 75;14.", repo.SwingSet3.JButtonInfo, new RecordItemIndex(20));
            repo.SwingSet3.JButton.Click("75;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.DoIt' at 32;13.", repo.SwingSet3.JPanel.DoItInfo, new RecordItemIndex(21));
            repo.SwingSet3.JPanel.DoIt.Click("32;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.DoItAgain' at 49;13.", repo.SwingSet3.JPanel.DoItAgainInfo, new RecordItemIndex(22));
            repo.SwingSet3.JPanel.DoItAgain.Click("49;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.TextField' at 64;18.", repo.SwingSet3.JPanel.TextFieldInfo, new RecordItemIndex(23));
            repo.SwingSet3.JPanel.TextField.Click("64;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.ButtonGo' at 20;10.", repo.SwingSet3.JPanel.ButtonGoInfo, new RecordItemIndex(24));
            repo.SwingSet3.JPanel.ButtonGo.Click("20;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.TfPassword1' at 75;10.", repo.SwingSet3.JPanel.TfPassword1Info, new RecordItemIndex(25));
            repo.SwingSet3.JPanel.TfPassword1.Click("75;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello'.", new RecordItemIndex(26));
            Keyboard.Press("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SwingSet3.JPanel.TfPassword2' at 28;16.", repo.SwingSet3.JPanel.TfPassword2Info, new RecordItemIndex(27));
            repo.SwingSet3.JPanel.TfPassword2.Click("28;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello'.", new RecordItemIndex(28));
            Keyboard.Press("hello");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
